[package]
name = "emojimarket_program"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
solana-program = "1.20.14"
borsh = "0.10"
borsh-derive = "0.10"
thiserror = "1.0"